Skeleton template for our Micro services
TeamNASSS/Contacts-Microservice pull request #2
Opened 2022-10-10 15:24 UTC by karayanni

Used the accepted way of defining routes and resources using flask_restful.
This is only the first step but still let me know WDYT and if you have suggestions for improvements

2022-10-11 12:56 UTC, satyamsharma requested changes
<img width="555" alt="image" src="https://user-images.githubusercontent.com/17713264/195096070-840e83d5-b18d-4888-9c7c-46cc45c63608.png">

post seems to return a 400 on my end, possibly because of a missing header

also, there is a redundant status 308 in the beginning when I ran test.py

2022-10-11 12:56 UTC, satyamsharma commented on main.py
> +api.add_resource(UserContactInfoApiResource, "/contactInfo/<string:userId>")
I like the aesthetics of decorator
e.g.
@app.route("/contactInfo/<userId>", methods=["GET"])

but we can discuss on Wednesday what everyone thinks

2022-10-11 12:56 UTC, satyamsharma commented on test.py
> +response = requests.post(base + 'contactInfo/', {"Email": "nice", "Id": 231, "phoneNumber": 9294612209})
we need to specify that it is a application/json type data

2022-10-12 14:16 UTC, karayanni commented on test.py
> +response = requests.post(base + 'contactInfo/', {"Email": "nice", "Id": 231, "phoneNumber": 9294612209})
I think it infers that automatically as the test is passing

2022-10-12 14:21 UTC, karayanni commented on test.py
> +response = requests.post(base + 'contactInfo/', {"Email": "nice", "Id": 231, "phoneNumber": 9294612209})
I added it explicitly as I agree it is better to explicit and checked that the header is added:
{'Content-Type': 'application/json', 'Content-Length': '41', 'Server': 'Werkzeug/2.0.3 Python/3.10.4', 'Date': 'Wed, 12 Oct 2022 14:20:34 GMT'}

2022-10-15 06:21 UTC, merged